version: '3.7'

### VueJS Utilities ##################################
vuejs:
    image: node:12
    ports: 
      - '8085:8080'
    volumes:
      - ${APP_CODE_PATH_HOST}:/data
    working_dir: /data/vuefood
    command: 'npm run serve'